# Generated by Django 4.2 on 2024-10-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_horas',
            field=models.PositiveIntegerField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=40, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=40, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estudiante.curso'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=40, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota_curso',
            field=models.PositiveIntegerField(null='false'),
            preserve_default='false',
        ),
    ]
